#un ejemplo que se puede usar .yml o .properties (hay un pluguin que te pasa un ode el otro solo tengo q hacer doble click aca en el intellij)
info:
    app:
        description: master spring boot
        name: Sping boot master class course
        version: 1.0.0
    company:
        name: NicoArdizzoliDEV
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info,env,beans,prometheus
    info:
        env:
            enabled: true
server:
    error:
        include-binding-errors: always
        include-message: always
        include-stacktrace: on_param
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
    main:
        banner-mode: 'off'
